function net = buildNetwork(trainData,trainLabels,dsVal,inputSize,...
    filterSize,numFilters,maxPool)  

batchSize = floor(length(trainLabels)/15);

layers = [
    imageInputLayer(inputSize,"Name","imageinput_1",'Normalization','none')
    convolution2dLayer([1 4],32,"Padding","same","Name","conv_1")
    batchNormalizationLayer("Name","batch_1")
    maxPooling2dLayer([1 3],"Name","pool_1","Padding","same")
    reluLayer("Name","relu_1")
    convolution2dLayer([1 4],32,"Padding","same","Name","conv_2")
    batchNormalizationLayer("Name","batch_2")
    maxPooling2dLayer([1 3],"Name","pool_2","Padding","same")
    reluLayer("Name","relu_2")
    convolution2dLayer([1 4],32,"Padding","same","Name","conv_3")
    batchNormalizationLayer("Name","batch_3")
    maxPooling2dLayer([1 3],"Name","pool_3","Padding","same")
    reluLayer("Name","relu_3")
    convolution2dLayer([1 4],32,"Padding","same","Name","conv_4")
    batchNormalizationLayer("Name","batch_4")
    maxPooling2dLayer([1 3],"Name","pool_4","Padding","same")
    fullyConnectedLayer(2,"Name","fc")
    softmaxLayer("Name","softmax")
    classificationLayer("Name","classoutput")];   

    %{
options = trainingOptions('sgdm',...
    'ExecutionEnvironment', 'parallel',...
    'MaxEpochs', 100,...
    'MiniBatchSize',batchSize,...
    'Shuffle', 'every-epoch',...
    'Verbose',1,...
    'VerboseFrequency',100,...
    'ValidationData',dsVal,...
    'ValidationFrequency',25,...
    'Momentum',0.5);
    %}
options = trainingOptions('adam',...
    'ExecutionEnvironment', 'parallel',...
    'MaxEpochs', 100,...
    'MiniBatchSize',batchSize,...
    'Shuffle', 'every-epoch',...
    'Verbose',1,...
    'VerboseFrequency',100,...
    'ValidationData',dsVal,...
    'ValidationFrequency',25,...
    'InitialLearnRate',0.001,...
    'L2Regularization',0.0005,...
    'Plots','training-progress');


net = trainNetwork(trainData,trainLabels,layers,options);

end
